name: OWASP ZAP Integration with GitHub Actions

on: [push, fork]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web apps / URLs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 2
     - run: git checkout HEAD^
          #ref: master

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://ea255871trial-dev-tacp-contracts-approuter.cfapps.us10-001.hana.ondemand.com/tacp-ui/index.html'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
