on:
  schedule:
    - cron: "20 16 * * *"
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:tests'
          target: 'https://transport-for-nsw-tacp-dev-development-dev-iam-flp-approuter.cfapps.ap10.hana.ondemand.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        